# Generated by Django 3.1.4 on 2021-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='soni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etiketika',
            name='soni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='idish',
            name='kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='karobka',
            name='soni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kirim',
            name='soni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kraska',
            name='ksoni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kraska',
            name='soni',
            field=models.IntegerField(),
        ),
    ]
