# Generated by Django 3.1.4 on 2021-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admines', '0002_auto_20210111_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idish',
            name='kg',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='idish',
            name='soni',
            field=models.IntegerField(),
        ),
    ]
